api:
  prefix: api

github:
  deviceCodeApiUrl: https://github.com/login/device/code
  oauthApiUrl: https://github.com/login/oauth/access_token
  headers:
    accept: 'application/json'
    'editor-version': 'Neovim/0.6.1'
    'editor-plugin-version': 'copilot.vim/1.16.0'
    'content-type': 'application/json'
    'user-agent': 'GithubCopilot/1.155.0'
    'accept-encoding': 'gzip,deflate,br'
  copilot:
    clientId: Iv1.b507a08c87ecfe98
    copilotApiUrl: https://api.githubcopilot.com
    headers:
      'Editor-Version': 'CopilotProxy/0.1.0'
      'Copilot-Integration-Id': 'vscode-chat'
      'Copilot-Vision-Request': 'true'
      'User-Agent': 'CopilotProxy'
      'host': 'api.githubcopilot.com'
  copilot_internal:
    tokenApiUrl: https://api.github.com/copilot_internal/v2/token
